#
# File:   Makefile
# Date:   2016-12-27
# Author: Andreas Mueller
#
# Description: Makefile for the Verilog DDS project.
#              Serves as entry point for all test and build scripts.
#

.PHONY: sim
sim:
	cd ./sim/iverilog/run && ./run_dds_tb.sh

.PHONY: syn
syn:
	echo "TODO"
