##############################################################################
## \file Makefile.iverilog
##
## \date 2015-04-05
##
## \author Andreas
##
## \brief Makefile template for Icarus Verilog projects.
##
## \details ...
##
## \see iverilog man pages.
##############################################################################

PROJECT_DIR=/home/andreas/projects/verilog/template
OUTPUT_DIR=./
IVERILOG_DIR=/bin/
SYNTHESIS=$(IVERILOG_DIR)/iverilog
TRANSLATE=$(IVERILOG_DIR)/iverilog
MAP=$(IVERILOG_DIR)/iverilog
PAR=$(IVERILOG_DIR)/iverilog
BITGEN=$(IVERILOG_DIR)/iverilog

compile:


synthesis: translate

translate: map

map: par

par: bitgen

bitgen:

.PHONY all
all:

.PHONY clean
clean:

.PHONY clean_docu
clean_docu:

.PHONY docu
docu:

.PHONY syntax_check
syntax_check:
